const SHOW_SIGN_UP_MODAL = 'SHOW_SIGN_UP_MODAL'
const HIDE_SIGN_UP_MODAL = 'HIDE_SIGN_UP_MODAL'

const CHANGE_LOGIN = 'CHANGE_LOGIN'

const SIGN_UP = 'SIGN_UP'
const LOG_OUT = 'LOG_OUT'

const LOAD_PROFILE = 'LOAD_PROFILE'
const DELETE_PROFILE = 'DELETE_PROFILE'
const UPDATE_PROFILE = 'UPDATE_PROFILE'

const REGISTER_APP = 'REGISTER_APP'
const REQUEST_PROFILE = 'REQUEST_PROFILE'

const LOAD_APPS = 'LOAD_APPS'
const ADD_APP = 'ADD_APP'
const REMOVE_APP = 'REMOVE_APP'

export {
  SHOW_SIGN_UP_MODAL,
  HIDE_SIGN_UP_MODAL,
  CHANGE_LOGIN,
  SIGN_UP,
  LOG_OUT,
  LOAD_PROFILE,
  DELETE_PROFILE,
  UPDATE_PROFILE,
  REGISTER_APP,
  REQUEST_PROFILE,
  LOAD_APPS,
  ADD_APP,
  REMOVE_APP,
}
