const SHOW_LOG_IN_MODAL = 'SHOW_LOG_IN_MODAL'
const HIDE_LOG_IN_MODAL = 'HIDE_LOG_IN_MODAL'

const SHOW_SIGN_UP_MODAL = 'SHOW_SIGN_UP_MODAL'
const HIDE_SIGN_UP_MODAL = 'HIDE_SIGN_UP_MODAL'

const CHANGE_LOGIN = 'CHANGE_LOGIN'
const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

const LOG_IN = 'LOG_IN'
const SIGN_UP = 'SIGN_UP'
const LOG_OUT = 'LOG_OUT'

const DELETE_PROFILE = 'DELETE_PROFILE'
const UPDATE_PROFILE = 'UPDATE_PROFILE'

export {
  SHOW_LOG_IN_MODAL,
  HIDE_LOG_IN_MODAL,
  SHOW_SIGN_UP_MODAL,
  HIDE_SIGN_UP_MODAL,
  CHANGE_LOGIN,
  CHANGE_PASSWORD,
  LOG_IN,
  SIGN_UP,
  LOG_OUT,
  DELETE_PROFILE,
  UPDATE_PROFILE,
}
