const SHOW_SIGN_UP_MODAL = 'SHOW_SIGN_UP_MODAL'
const HIDE_SIGN_UP_MODAL = 'HIDE_SIGN_UP_MODAL'
const SHOW_SIGN_IN_MODAL = 'SHOW_SIGN_IN_MODAL'
const HIDE_SIGN_IN_MODAL = 'HIDE_SIGN_IN_MODAL'
const SHOW_ADD_APP_MODAL = 'SHOW_ADD_APP_MODAL'
const HIDE_ADD_APP_MODAL = 'HIDE_ADD_APP_MODAL'

const CHANGE_USERNAME = 'CHANGE_USERNAME'
const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

const LOAD_USERS = 'LOAD_USERS'
const SIGN_UP = 'SIGN_UP'
const SIGN_UP_VALIDATION = 'SIGN_UP_VALIDATION'
const SIGN_IN = 'SIGN_IN'
const SIGN_IN_VALIDATION = 'SIGN_IN_VALIDATION'
const SIGN_OUT = 'SIGN_OUT'

const DELETE_PROFILE = 'DELETE_PROFILE'
const UPDATE_PROFILE = 'UPDATE_PROFILE'

const LOAD_APPS = 'LOAD_APPS'
const SET_ADD_APP_MODAL_STEP = 'SET_ADD_APP_MODAL_STEP'
const REGISTER_APP = 'REGISTER_APP'
const REQUEST_PROFILE = 'REQUEST_PROFILE'
const ACCEPT_APP = 'ACCEPT_APP'
const DECLINE_APP = 'DECLINE_APP'

const REMOVE_APP = 'REMOVE_APP'

export {
  SHOW_SIGN_UP_MODAL,
  HIDE_SIGN_UP_MODAL,
  SHOW_SIGN_IN_MODAL,
  HIDE_SIGN_IN_MODAL,
  SHOW_ADD_APP_MODAL,
  HIDE_ADD_APP_MODAL,
  CHANGE_USERNAME,
  CHANGE_PASSWORD,
  LOAD_USERS,
  SIGN_UP,
  SIGN_UP_VALIDATION,
  SIGN_IN,
  SIGN_IN_VALIDATION,
  SIGN_OUT,
  DELETE_PROFILE,
  UPDATE_PROFILE,
  LOAD_APPS,
  SET_ADD_APP_MODAL_STEP,
  REGISTER_APP,
  REQUEST_PROFILE,
  ACCEPT_APP,
  DECLINE_APP,
  REMOVE_APP,
}
