const START_SIGN_OUT = 'START_SIGN_OUT'
const SIGN_OUT = 'SIGN_OUT'

const START_UPDATE_ACCOUNT = 'START_UPDATE_ACCOUNT'
const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

const START_DELETE_ACCOUNT = 'START_DELETE_ACCOUNT'
const DELETE_ACCOUNT = 'DELETE_ACCOUNT'

export {
  START_SIGN_OUT,
  SIGN_OUT,
  START_UPDATE_ACCOUNT,
  UPDATE_ACCOUNT,
  START_DELETE_ACCOUNT,
  DELETE_ACCOUNT,
}
