const FETCH_CLAIM = 'FETCH_CLAIM'
const SET_CLAIM = 'SET_CLAIM'

const START_REMOVE_APP = 'START_REMOVE_APP'
const REMOVE_APP = 'REMOVE_APP'

const SET_REDIRECT_TO_APPS = 'SET_REDIRECT_TO_APPS'

export { FETCH_CLAIM, SET_CLAIM, START_REMOVE_APP, REMOVE_APP, SET_REDIRECT_TO_APPS }
