const FETCH_APP = 'FETCH_APP'
const SET_APP = 'SET_APP'

const START_REMOVE_APP = 'START_REMOVE_APP'
const REMOVE_APP = 'REMOVE_APP'

const SET_REDIRECT_TO_APPS = 'SET_REDIRECT_TO_APPS'

export { FETCH_APP, SET_APP, START_REMOVE_APP, REMOVE_APP, SET_REDIRECT_TO_APPS }
