const SHOW_ADD_APP_MODAL = 'SHOW_ADD_APP_MODAL'
const HIDE_ADD_APP_MODAL = 'HIDE_ADD_APP_MODAL'

const SHOW_REMOVE_APP_MODAL = 'SHOW_REMOVE_APP_MODAL'
const SET_REMOVE_APP_MODAL_CLAIM = 'SET_REMOVE_APP_MODAL_CLAIM'
const HIDE_REMOVE_APP_MODAL = 'HIDE_REMOVE_APP_MODAL'

const FETCH_APPS = 'FETCH_APPS'
const SET_APPS = 'SET_APPS'

const SET_ADD_APP_MODAL_STEP = 'SET_ADD_APP_MODAL_STEP'
const SET_ADD_APP_MODAL_APP_REQUEST = 'SET_ADD_APP_MODAL_APP_REQUEST'
const ACCEPT_APP = 'ACCEPT_APP'
const DECLINE_APP = 'DECLINE_APP'

const START_REMOVE_APP = 'START_REMOVE_APP'
const REMOVE_APP = 'REMOVE_APP'

export {
  SHOW_ADD_APP_MODAL,
  HIDE_ADD_APP_MODAL,
  SHOW_REMOVE_APP_MODAL,
  SET_REMOVE_APP_MODAL_CLAIM,
  HIDE_REMOVE_APP_MODAL,
  FETCH_APPS,
  SET_APPS,
  SET_ADD_APP_MODAL_STEP,
  SET_ADD_APP_MODAL_APP_REQUEST,
  ACCEPT_APP,
  DECLINE_APP,
  START_REMOVE_APP,
  REMOVE_APP,
}
