const FETCH_PUBLIC_ACCOUNTS = 'FETCH_PUBLIC_ACCOUNTS'
const SET_PUBLIC_ACCOUNTS = 'SET_PUBLIC_ACCOUNTS'

const START_SIGN_UP = 'START_SIGN_UP'
const SIGN_UP = 'SIGN_UP'

const START_SIGN_IN = 'START_SIGN_IN'
const SIGN_IN = 'SIGN_IN'

const SET_REGISTER_APP_LINK = 'SET_REGISTER_APP_LINK'

export {
  FETCH_PUBLIC_ACCOUNTS,
  SET_PUBLIC_ACCOUNTS,
  START_SIGN_UP,
  SIGN_UP,
  START_SIGN_IN,
  SIGN_IN,
  SET_REGISTER_APP_LINK,
}
