const FETCH_PUBLIC_PROFILES = 'FETCH_PUBLIC_PROFILES'
const SET_PUBLIC_PROFILES = 'SET_PUBLIC_PROFILES'

const START_SIGN_UP = 'START_SIGN_UP'
const SIGN_UP = 'SIGN_UP'

const START_SIGN_IN = 'START_SIGN_IN'
const SIGN_IN = 'SIGN_IN'

export {
  FETCH_PUBLIC_PROFILES,
  SET_PUBLIC_PROFILES,
  START_SIGN_UP,
  SIGN_UP,
  START_SIGN_IN,
  SIGN_IN,
}
