const FETCH_PERSONA = 'FETCH_PERSONA'
const SET_PERSONA = 'SET_PERSONA'

const FETCH_PERSONA_APPS = 'FETCH_PERSONA_APPS'
const SET_PERSONA_APPS = 'SET_PERSONA_APPS'

const START_CREATE_PERSONA = 'START_CREATE_PERSONA'
const START_UPDATE_PERSONA = 'START_UPDATE_PERSONA'
const START_DELETE_PERSONA = 'START_DELETE_PERSONA'

const SHOW_EXPORT_PERSONA_MODAL = 'SHOW_EXPORT_PERSONA_MODAL'
const HIDE_EXPORT_PERSONA_MODAL = 'HIDE_EXPORT_PERSONA_MODAL'
const SET_EXPORT_PERSONA_TEXT = 'SET_EXPORT_PERSONA_TEXT'

const SET_REDIRECT = 'SET_REDIRECT'

export {
  FETCH_PERSONA,
  SET_PERSONA,
  FETCH_PERSONA_APPS,
  SET_PERSONA_APPS,
  START_CREATE_PERSONA,
  START_UPDATE_PERSONA,
  START_DELETE_PERSONA,
  SHOW_EXPORT_PERSONA_MODAL,
  HIDE_EXPORT_PERSONA_MODAL,
  SET_EXPORT_PERSONA_TEXT,
  SET_REDIRECT,
}
