const FETCH_PERSONAS = 'FETCH_PERSONAS'
const SET_PERSONAS = 'SET_PERSONAS'

const FETCH_PERSONAS_APPS = 'FETCH_PERSONAS_APPS'
const SET_PERSONAS_APPS = 'SET_PERSONAS_APPS'

export { FETCH_PERSONAS, SET_PERSONAS, FETCH_PERSONAS_APPS, SET_PERSONAS_APPS }
