const FETCH_PROFILE = 'FETCH_PROFILE'
const SET_PROFILE = 'SET_PROFILE'

const START_DELETE_PROFILE = 'START_DELETE_PROFILE'
const DELETE_PROFILE = 'DELETE_PROFILE'

const START_UPDATE_PROFILE = 'START_UPDATE_PROFILE'
const UPDATE_PROFILE = 'UPDATE_PROFILE'

const SHOW_EXPORT_PROFILE_MODAL = 'SHOW_EXPORT_PROFILE_MODAL'
const HIDE_EXPORT_PROFILE_MODAL = 'HIDE_EXPORT_PROFILE_MODAL'
const SET_EXPORT_PROFILE_TEXT = 'SET_EXPORT_PROFILE_TEXT'

export {
  FETCH_PROFILE,
  SET_PROFILE,
  START_DELETE_PROFILE,
  DELETE_PROFILE,
  START_UPDATE_PROFILE,
  UPDATE_PROFILE,
  SHOW_EXPORT_PROFILE_MODAL,
  HIDE_EXPORT_PROFILE_MODAL,
  SET_EXPORT_PROFILE_TEXT,
}
