const FETCH_PROFILE = 'FETCH_PROFILE'
const SET_PROFILE = 'SET_PROFILE'

const START_SIGN_OUT = 'START_SIGN_OUT'
const SIGN_OUT = 'SIGN_OUT'

const START_DELETE_PROFILE = 'START_DELETE_PROFILE'
const DELETE_PROFILE = 'DELETE_PROFILE'

const START_UPDATE_PROFILE = 'START_UPDATE_PROFILE'
const UPDATE_PROFILE = 'UPDATE_PROFILE'

const START_UPDATE_PASSWORD = 'START_UPDATE_PASSWORD'
const UPDATE_PASSWORD = 'UPDATE_PASSWORD'

const SHOW_EXPORT_PROFILE_MODAL = 'SHOW_EXPORT_PROFILE_MODAL'
const HIDE_EXPORT_PROFILE_MODAL = 'HIDE_EXPORT_PROFILE_MODAL'
const SET_EXPORT_PROFILE_TEXT = 'SET_EXPORT_PROFILE_TEXT'

export {
  FETCH_PROFILE,
  SET_PROFILE,
  START_SIGN_OUT,
  SIGN_OUT,
  START_DELETE_PROFILE,
  DELETE_PROFILE,
  START_UPDATE_PROFILE,
  UPDATE_PROFILE,
  START_UPDATE_PASSWORD,
  UPDATE_PASSWORD,
  SHOW_EXPORT_PROFILE_MODAL,
  HIDE_EXPORT_PROFILE_MODAL,
  SET_EXPORT_PROFILE_TEXT,
}
